version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      DATABASE_URL: "postgres://postgres:password@postgres:5432/mydb"
    ports:
      - "5431:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
networks:
  backend:
